name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
        stack-setup-ghc: true
        stack-no-global: true
    - name: Cache stack
      uses: actions/cache@v1
      env:
        cache-name: cache-stack
      with:
        path: ~/.stack
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Cache cabal
      uses: actions/cache@v1
      env:
        cache-name: cache-cabal
      with:
        path: ~/.cabal
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/*.cabal') }}-${{ hashFiles('**/cabal.project') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    - name: Install Debian dependencies
      run: sudo apt-get update && sudo apt-get install -y verilator g++ srecord gcc-riscv64-unknown-elf yosys #nextpnr-ice40
    - name: Install Stack dependencies
      run: |
        stack update
        stack build --only-dependencies
    - name: Build RISC-V ISA tests
      run: cd riscv-tests && make
    - name: Run tests
      run: cd testbench && make
    - name: Test synthesis
      run: cd synth && make

